### ISSUE TITLE
AJT Furigana won't load and displays error upon opening Anki

### ISSUE THREAD

**Issue by sdufus** [Ajatt-Tools/Japanese#1]
Just upgraded the AJT Furigana plugin. Restarted Anki, and immediately received two pop-up error windows. Happens each time I open the program.

-Windows 10 x64 Pro
-Anki version 2.1.54

Attached is a screenshot of the two pop-ups I get as soon as the program loads.
![image](https://user-images.githubusercontent.com/80500984/223602705-9c985acb-833d-46f7-89bc-046d589be516.png)

**Comment by tatsumoto-ren** [comment]
I currently can't reproduce this error, but I'll try on a different computer.
