### ISSUE TITLE
"generate furigana in the field" results with "inconsistent state" for a new note

### ISSUE THREAD

**Issue by notaz** [Ajatt-Tools/Japanese#10]
I have the "Furigana button" (振) enabled, and whenever I press it on the "Add" dialog, Anki throws "your database appears to be in a inconsistent state" message box, and the terminal prints "No such note: '0'". The button works fine if I edit an existing note. It seemed to break on some update as it used to work fine some time ago.

Seems to be related to #9. I use Anki 23.12.1 with the latest AJT from ankiweb.

**Comment by tatsumoto-ren** [comment]
Please read: [issue.md](https://github.com/Ajatt-Tools/Japanese/blob/main/.github/ISSUE_TEMPLATE/issue.md)

This is caused by the work related to https://github.com/Ajatt-Tools/Japanese/issues/7 and needs fixing.
