### ISSUE TITLE
Mecab issue with path?

### ISSUE THREAD

**Issue by ONEsuzuki** [Ajatt-Tools/Japanese#11]
- The add-on stopped working?
Part of it can't find the path it seems, my pc is in Japanese with UTF8 optional characters enabled that didn't resolve the issue. It generated furigana for the vocab just not the sentence field, all fields are linked to the note type correctly. I did some searching around the web but feel I need some help to resolve this issue. Thanks in advance.
1) OS name
エディション	Windows 11 Pro
2) OS version
バージョン	23H2
インストール日	‎18/‎03/‎2024
OS ビルド	22631.3296
エクスペリエンス	Windows Feature Experience Pack 1000.22687.1000.0
3) Anki version
バージョン ⁨23.12.1 (1a1d4d54)⁩
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
4) Logs
‪tagger.cpp(151) [load_dictionary_resource(param)] param.cpp(71) [ifs] no such file or directory: C:\Users\RED\AppData\Roaming\Anki2\addons21\1344485230\mecab_controller\support\mecabrc‬
5) Screenshots, if applicable
<img width="470" alt="スクリーンショット 2024-03-19 172017" src="https://github.com/Ajatt-Tools/Japanese/assets/111155695/ec4dd5e5-e725-4d1e-9ad9-981e160ec447">
<img width="128" alt="スクリーンショット 2024-03-19 172053" src="https://github.com/Ajatt-Tools/Japanese/assets/111155695/3a14d274-7967-4e67-8b1c-7651f10ff252">

**Comment by tatsumoto-ren** [comment]
> no such file or directory: C:\Users\RED\AppData\Roaming\Anki2\addons21\1344485230\mecab_controller\support\mecabrc‬

I thought we already had a check for that in place, here https://github.com/Ajatt-Tools/mecab_controller/blob/4fec869a5524f473e1749a5cc6f89c4545a62b6b/basic_mecab_controller.py#L13

**Comment by ONEsuzuki** [comment]
I tried the "Japanese support addon" and it gave me this error:
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22631
Unexpected output from mecab. Perhaps your Windows username contains non-Latin text?: 'tagger.cpp(151) [load_dictionary_resource(param)] param.cpp(71) [ifs] no such file or directory: C:\\Users\\RED\\AppData\\Roaming\\Anki2\\addons21\\3918629684\\support\\mecabrc'
Traceback (most recent call last):
I know this isn't you're addon, but it's having the same issue locating the "mecab" on the Japanese support addon page he said 
"If you receive a message about non-Latin text, it is because the reading support does not work when your Windows login name contains characters from other languages. If you create a new Windows login using A-Z characters, or rename your existing login folder (for advanced users only!), it should resolve the problem." 
And my windows login name is in Japanese, I reckon this is the same problem, you don't seem to like windows much but do you know of a work around, or could it be fixed to work with a Japanese sign in name, if it is the problem?

**Comment by tatsumoto-ren** [comment]
the Japanese support addon by Damien Elmes basically some core features with this addon. The error you're getting is the same.

**Comment by ONEsuzuki** [comment]
Thanks for the quick replies are change it now, have a nice evening.
