### ISSUE TITLE
Multiple furigana options generated: select only one and selecting the correct reading

### ISSUE THREAD

**Issue by kanjieater** [Ajatt-Tools/Japanese#8]
![image](https://github.com/Ajatt-Tools/Japanese/assets/32607317/d0417d4f-98a1-4795-844d-aff45404de3b)

Instead of generating 
術[じゅつ] 式[しき]

The addon generates
術[じゅつ, すべ] 式[しき]

1. Is it possible to only ever generate one reading? I've been noticing sometimes the tool will generate many readings, which can throw off the spacing inside of anki, as the furigana get's too long. I get that sometimes multiple readings are appropriate and the tool isn't aware of the context and which should be used, but I would still like a way to pick just the first one even if it's inaccurate (like the standard Japanese add-on does).

Ideal spacing
![image](https://github.com/Ajatt-Tools/Japanese/assets/32607317/31b73860-7c9e-4e2a-a7ce-0d4d9ab84135)
AJT Spacing:
![image](https://github.com/Ajatt-Tools/Japanese/assets/32607317/b35db2d3-7103-41b9-b105-acfe59e06043)
![image](https://github.com/Ajatt-Tools/Japanese/assets/32607317/3e1296b7-8a02-4d48-ae36-0ebf5b4929b0)

2. Suggestion: Given how often I see the tool generating the wrong furigana, like `術[じゅつ, すべ] 式[しき]`, I'm wondering if it would be worth-while to just have a list of words and their reading in the tool, that's ordered by frequency. I did something similar in my Kindle add-on. I get that it's not elegent to have a giant list of words and readings read into the add-on from a text file, but it's been far more accurate than even mecab alone in my experience.

**Comment by tatsumoto-ren** [comment]
Note that usually we don't discuss issues on GitHub. DJT space exists for this purpose.

****

> the furigana get's too long

This can happen when the  add-on is not used correctly, namely when your note type does not come from Ajatt-Tools. 
Normally, when there's more than one reading, they stack on top of each other. 

![screenshot](https://github.com/Ajatt-Tools/Japanese/assets/69171671/6b9aeb94-8c28-4c1e-9027-c8f1bab9da2f)
(go to AJT > Download example deck)

As a workaround you can go to Settings and change reading separator to `<br>` but it won't have the same effect.

> Is it possible to only ever generate one reading?

In furigana options change "maximum results" to 1.

> a list of words and their reading in the tool, that's ordered by frequency.

I'm pretty sure we already output readings in the order of their frequency so the first one should be the most common.

**Comment by kanjieater** [comment]
So what would the recommendation be for something like the example where it's wrong
術[じゅつ, すべ] 式[しき]

**Comment by tatsumoto-ren** [comment]
I think it's nice to have more than one reading visible though. I have maximum results set to 4. Sometimes, if I don't like the results, I edit them afterwards and remove incorrect readings.
